### ISSUE TITLE
Mapper::toCollection() breaks PHPStan

### ISSUE THREAD

**Issue by stpnkcrk** [nextras/orm-phpstan#17]
PHPStan 0.12.40
Nextras\Orm 4.0-RC1
Nextras\Orm-PHPStan dev-master

This makes PHPStan with active nextras/orm-phpstan extension to freeze when analysing the file.

```php
<?php declare(strict_types=1);

namespace App\Model\System;

use Nextras\Orm\Collection\ICollection;
use Nextras\Orm\Mapper\Mapper;

final class LogMapper extends Mapper
{
    public function findAllWithTranslatedIps(): ICollection
    {
        return $this->toCollection(
            $this->builder()->addSelect('inet6_ntoa([ip]) as [ip]')
        );
    }
}
```

The issue persists even with just `$this->builder()` suggesting error isn't in the custom select part.

**Comment by hrach** [comment]
Well, the issue here is we try to guess the name of repository. What is FQN name of LogsRepository?

**Comment by stpnkcrk** [comment]
App\Model\System\Log (Entity)
App\Model\System\LogMapper
App\Model\System\LogRepository

**Comment by stpnkcrk** [comment]
It seems it's failing on `$mapperClass = \get_parent_class($mapperClass);` in the `MapperMethodReturnTypeExtension.php` as that returns false on my machine and therefore it falls into infinite loop.

```php
$mapperClass = $mapper->getClassName();
do {
	/** @phpstan-var class-string<\Nextras\Orm\Repository\Repository> $repositoryClass */
	$repositoryClass = \str_replace('Mapper', 'Repository', $mapperClass);
	$mapperClass = \get_parent_class($mapperClass);
	assert(is_string($mapperClass));
} while (!\class_exists($repositoryClass) && $mapperClass !== DbalMapper::class);
```

`$repositoryClass` is recognised correctly as `App\Model\System\LogRepository`.

**Comment by hrach** [comment]
What is your definition of LogRepository? What does it extend?

**Comment by stpnkcrk** [comment]
```php
<?php declare(strict_types=1);

namespace App\Model\System;

use Nextras\Orm\Collection\ICollection;
use Nextras\Orm\Repository\Repository;

/**
 * @method ICollection|Log[] findAllWithTranslatedIps()
 */
final class LogRepository extends Repository
{
    public static function getEntityClassNames(): array
    {
        return [Log::class];
    }
}
```

**Comment by stpnkcrk** [comment]
[nextras-orm-phpstan-failing-demo.zip](https://github.com/nextras/orm-phpstan/files/5149331/nextras-orm-phpstan-failing-demo.zip)

**Comment by hrach** [comment]
I somehow know where the bug is, will try to fix asap. Thanks for reporting.

**Comment by hrach** [comment]
Fixed https://github.com/nextras/orm-phpstan/commit/c7a64f8897d6dce40b762a18bebae5e415edc3c8

**Comment by stpnkcrk** [comment]
Thank you very much!!!
