### ISSUE TITLE
phpstan cries with Nextras ORM 4

### ISSUE THREAD

**Issue by milsorm** [nextras/orm-phpstan#22]
```
     Child process error (exit code 255): PHP Fatal error:  Class Nextras\Orm\Mapper\Dbal\DbalCollection contains 2 abstract methods
     and must therefore be declared abstract or implement the remaining methods (Nextras\Orm\Collection\ICollection::getByChecked,
     Nextras\Orm\Collection\ICollection::getByIdChecked) in
     vendor/nextras/orm/src/Mapper/Dbal/DbalCollection.php on line 23
     Fatal error: Class Nextras\Orm\Mapper\Dbal\DbalCollection contains 2 abstract methods and must therefore be declared abstract or
     implement the remaining methods (Nextras\Orm\Collection\ICollection::getByChecked,
     Nextras\Orm\Collection\ICollection::getByIdChecked) in
     vendor/nextras/orm/src/Mapper/Dbal/DbalCollection.php on line 23
```

**Comment by hrach** [comment]
It seems to be some cache issue of PhpStan after upgrade. 🤔 See DbalCollection - it does not contain abstract methods now. https://github.com/nextras/orm/blob/v4.0.1/src/Collection/DbalCollection.php

**Comment by milsorm** [comment]
Probably old version of DbalCollection because I have not getByChecked implementation there. I have to check how it is upgraded by composer.

**Comment by milsorm** [comment]
Hmm, complaints are against Nextras\Orm\Mapper\Dbal\DbalCollection which differs from Nextras\Orm\Collection\DbalCollection :-(

**Comment by milsorm** [comment]
OK, completely removed, refreshed from github and everything is OK now. Sorry for bothering.

**Comment by hrach** [comment]
👍 Good :)
