### ISSUE TITLE
Incompatible types: Expected property

### ISSUE THREAD

**Issue by mareksloser** [nextras/orm-phpstan#27]
Hello,

`Incompatible types: Expected property of type '\App\Database\Entity\Project', '\Nextras\Orm\Entity\IEntity|null' provided`

How to solve this phpstan msg? Static analyse give me this "error" 

![image](https://user-images.githubusercontent.com/10614710/175925580-9840afb1-b5cf-42ec-a611-fcd971acb36a.png)

Thank you,

**Comment by hrach** [comment]
You have to use getByIdChecked() method (available in form 4.0+)

I am really sorry to respond so late to this, I missed thath.
